/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, useScroll } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'
import * as THREE from 'three'

export function Model(props) {
  const { nodes } = useGLTF('/logo.glb')
  const groupRef = useRef()
  const scroll = useScroll()

  useFrame((state, delta) => {
    // 1. Get Scroll Position
    const scrollOffset = scroll?.offset || 0; // Safe fallback if scroll is missing

    if (groupRef.current) {
        // 2. Gentle Float (Bobbing up and down)
        groupRef.current.position.y = Math.sin(state.clock.elapsedTime * 0.5) * 0.1;
        
        // 3. Tilt with Scroll
        // As you scroll down, the logo tilts up to look at you
        groupRef.current.rotation.x = scrollOffset * 0.5;
        
        // 4. Subtle Mouse Follow (Optional "Alive" feel)
        // Adds a tiny bit of rotation on Y axis constantly
        groupRef.current.rotation.y = Math.sin(state.clock.elapsedTime * 0.2) * 0.1;
    }
  })

  return (
    <group {...props} dispose={null} ref={groupRef}>
      
      {/* 1. "DeWhitt" - Brushed Gold */}
      <mesh 
        geometry={nodes.Logo_Main.geometry} 
        position={[0.094, 0.25, -0.891]} // Adjusted Y slightly up
        rotation={[Math.PI / 2, 0, 0]}   // Flips it upright
        scale={1.5}
        castShadow 
        receiveShadow
      >
          <meshStandardMaterial 
            color="#FFD700"        // Classic Gold
            metalness={1.0}        // 100% Metal
            roughness={0.3}        // Brushed texture (not a perfect mirror)
            envMapIntensity={1.5}  // Reflects the "City" lights
          />
      </mesh>

      {/* 2. "DESIGNS" - Matte Black */}
      <mesh 
        geometry={nodes.Logo_Sub.geometry} 
        position={[0.022, -0.75, 1.159]} // Adjusted Y slightly down
        rotation={[Math.PI / 2, 0, 0]}
        scale={1.5}
        receiveShadow 
      >
          <meshStandardMaterial 
            color="#050505"        // Deep Black
            roughness={1.0}        // Zero shine (Rubber/Velvet look)
            metalness={0.0}
          />
      </mesh>

    </group>
  )
}

useGLTF.preload('/logo.glb')